name: Post Fitbit summary to Twitter
on:
  schedule:
   - cron: '5 14 * * *' # 23:05 JST
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib
          pip install tweepy
          pip install google-cloud-storage
      - name: Post summary to Twitter
        run: |
          echo -n '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' > key.json
          python main.py
        env: 
          GOOGLE_APPLICATION_CREDENTIALS: key.json
          TW_CONSUMER_KEY: ${{ secrets.TW_CONSUMER_KEY }}
          TW_CONSUMER_SECRET: ${{ secrets.TW_CONSUMER_SECRET }}
          TW_ACCESS_TOKEN: ${{ secrets.TW_ACCESS_TOKEN }}
          TW_ACCESS_TOKEN_SECRET: ${{ secrets.TW_ACCESS_TOKEN_SECRET }}
