name: Post Fitbit summary to Twitter
on:
  schedule:
   - cron: '5 14 * * *' # 23:05 JST
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib
          pip install tweepy
          pip install google-cloud-storage
      - name: Post summary to Twitter
        run: |
          python main.py
        env: 
          TWITTER_CONSUMER_KEY: ${{ secrets.TW_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TW_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TW_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TW_ACCESS_TOKEN_SECRET }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}